// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL2GEnAjqU2G5f5BEjGXVDeHeGXy4C9bQ',
    appId: '1:872721218590:web:111f16fbe7c8a4f351820f',
    messagingSenderId: '872721218590',
    projectId: 'ruraltech10',
    authDomain: 'ruraltech10.firebaseapp.com',
    databaseURL: 'https://ruraltech10-default-rtdb.firebaseio.com',
    storageBucket: 'ruraltech10.firebasestorage.app',
    measurementId: 'G-8HVB4MLLEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUM_i4VGTaSvIc5INNMjvIJV0cAyN1VTY',
    appId: '1:872721218590:android:6c131a689af2a9b851820f',
    messagingSenderId: '872721218590',
    projectId: 'ruraltech10',
    databaseURL: 'https://ruraltech10-default-rtdb.firebaseio.com',
    storageBucket: 'ruraltech10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_GcGKK4gYiwzOv_E0dfkmokPAWbhu4Bo',
    appId: '1:872721218590:ios:20008cba37cbb2c351820f',
    messagingSenderId: '872721218590',
    projectId: 'ruraltech10',
    databaseURL: 'https://ruraltech10-default-rtdb.firebaseio.com',
    storageBucket: 'ruraltech10.firebasestorage.app',
    iosBundleId: 'com.example.ruraltechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_GcGKK4gYiwzOv_E0dfkmokPAWbhu4Bo',
    appId: '1:872721218590:ios:20008cba37cbb2c351820f',
    messagingSenderId: '872721218590',
    projectId: 'ruraltech10',
    databaseURL: 'https://ruraltech10-default-rtdb.firebaseio.com',
    storageBucket: 'ruraltech10.firebasestorage.app',
    iosBundleId: 'com.example.ruraltechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL2GEnAjqU2G5f5BEjGXVDeHeGXy4C9bQ',
    appId: '1:872721218590:web:1731a4fe5d01dd9f51820f',
    messagingSenderId: '872721218590',
    projectId: 'ruraltech10',
    authDomain: 'ruraltech10.firebaseapp.com',
    databaseURL: 'https://ruraltech10-default-rtdb.firebaseio.com',
    storageBucket: 'ruraltech10.firebasestorage.app',
    measurementId: 'G-SR0V580M48',
  );

}