#pragma once

#define RT_CFG_WIFI_OTA_DEFAULT_ENABLED false
#define RT_CFG_DEFAULT_PROPERTY_ID "T0xeG8WQHwJRI6H3t7vr"
#define RT_CFG_DEFAULT_PROPERTY_SCOPE_ID "9FFFC95AA1624895"
#define RT_CFG_DEFAULT_MATRIX_GATEWAY_ID "192.168.4.1"
#define RT_CFG_DEFAULT_BINDING_VERSION 1
